# Central configuration and versioning settings
# used for all pipelines
variables:
- name: 'riVariant' # Reference implementation variant - each repository should have its own identification. This value is surfaced to the UI.
  value: 'foundational-connected'

- name: 'terraformVersion'    # Terraform Version
  value: '1.6.2-*'
- name: 'kubernetesVersion'   # kubernetes version used for aks clusters
  value: '1.28.5'
- name: 'helmVersion'         # helm package manager version
  value: 'v3.14.0'
- name: 'ingressNginxVersion' # nginx ingress controller helm chart version
  value: '4.7.3'
- name: 'certManagerVersion'  # cert-manager helm chart version
  value: 'v1.13.3'
- name: 'dotnetSdkVersion'    # dotnet sdk version
  value: '8.0.201'
- name: 'uiAppNodeVersion'    # nodejs version for the UI app
  value: '18.x'
- name: 'testsNodeVersion'    # nodejs version used for smoketests / playwright
  value: '14.x'

- name: 'workloadNamespace'   # K8s namespace for workload deployment
  value: 'workload'
- name: 'ingressNamespace'
  value: 'ingress-nginx'

- name: 'aksPrivateLinkServiceName' # Name of the private link service which gets created by AKS
  value: 'aks-ingress-pls'

# Docker image names and paths to the Dockerfiles for the different components
- name: 'catalogserviceDockerfile'
  value: 'AlwaysOn.CatalogService/Dockerfile'
- name: 'catalogserviceImageName'
  value: 'alwayson/catalogservice'
- name: 'backgroundprocessorDockerfile'
  value: 'AlwaysOn.BackgroundProcessor/Dockerfile'
- name: 'backgroundprocessorImageName'
  value: 'alwayson/backgroundprocessor'
- name: 'healthserviceDockerfile'
  value: 'AlwaysOn.HealthService/Dockerfile'
- name: 'healthserviceImageName'
  value: 'alwayson/healthservice'

# Others
- name: 'smokeTestRetryCount' # How many times a request in the smoke tests is retried before declared as failed (retries HTTP response codes from 400-599 as well as issues like certificate errors)
  value: '20'
- name: 'smokeTestRetryWaitSeconds' # How long to wait between each retry of the smoke tests
  value: '60'
- name: 'skipComponentGovernanceDetection' # This is a Microsoft-specific setting. Having this in place ensures we don't create work items with CELA every time we use an open-source component
  value: 'true'