# Central configuration settings
# used for E2E environment pipelines - test
variables:

# Resource prefix for this environment
- name:  'prefix'
  value: 'lde001'          # <===== CHANGE THIS! Must not be longer than 6 characters! Needs to be a unique prefix

# The first value in 'stampLocations' is the primary region used for global services.
# IMPORTANT! Changing the primary region (first value) is a BREAKING change and will destroy CosmosDB and Front Door.
- name: 'stampLocations'
  value: '["uksouth","swedencentral"]'    # Check which regions are valid. There is a list in /src/infra/README.md

# Terraform state variables
- name:  'terraformResourceGroup'
  value: 'ldeconnected-tf-rg'      # <===== CHANGE THIS VALUE IF NEEDED
- name:  'terraformStorageAccount'
  value: '$(prefix)tfstate'              # <===== CHANGE THIS VALUE! Needs to be a globally unique name

# Other settings
- name:  'contactEmail'
  value: 'chris@lde.bezencon.net'  # <===== CHANGE THIS VALUE TO ONE OF YOUR REAL EMAIL ADDRESSES (OR A GROUP)!

  # Custom DNS name settings
- name: 'envDnsZoneRG'
  value: 'rg-mccdns'                         # <===== CHANGE THIS VALUE
- name: 'envDomainName'
  value: 'mcce2e.bezencon.net'     # <===== CHANGE THIS VALUE
